name: Daily Selenium Java Test

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build dependencies (skip tests)
        run: mvn clean install -DskipTests

      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Get Chrome major version
        id: chrome
        run: |
          FULL_VERSION=$(google-chrome --version | awk '{print $3}')
          MAJOR_VERSION=$(echo $FULL_VERSION | cut -d. -f1)
          echo "CHROME_VERSION=$MAJOR_VERSION" >> $GITHUB_ENV

      - name: Set up ChromeDriver
        uses: actions/setup-chromedriver@v2

      - name: Run Selenium tests
        run: mvn test
